---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: puppet_apply
#  puppet_version: latest
  manifests_path: test/integration
  modules_path: modules
#  hiera_data_path: hieradata

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    manifest: defaut/init.pp
