---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: puppet_apply
#  puppet_version: latest
  manifests_path: test/integration
  modules_path: modules
#  hiera_data_path: hieradata

platforms:
  - name: centos-7.2
    driver_config:
      provision_command:
        - /usr/bin/systemctl enable sshd
        - yum update -y
        - yum install -y net-tools tar initscripts #initscipts - needed to manage services
      run_command: /usr/sbin/init
  - name: centos-6.7
    driver_config:
      provision_command:
#        - /usr/bin/systemctl enable sshd
        - yum update -y
        - yum install -y net-tools tar initscripts #initscipts - needed to manage services
      run_command: /sbin/init

suites:
  - name: multiple-instances
    manifest: multiple-instances/init.pp

