---
sudo: false
language: ruby
cache:
  bundler: true
services:
  - docker
install:
  - bundle install #You need this to install the dependencies in the gemfile
  - librarian-puppet install
rvm:
  - 2.3.1
script:
  - kitchen test
  - puppet-lint --relative manifests
  - puppet-lint --relative test

branches:
  only:
    - master # Sensible default
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
